### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by hatemragab** [AhmedAlYousif/auto_direction#1]
is there plan to Migrate to Null Safety

**Comment by lutfiatrash** [comment]
Same problem
I hope we can get a new update as soon as possible

**Comment by AliHoseinpoor** [comment]
please support null safety

**Comment by hatemragab** [comment]
I go through the code i will migrate it soon

**Comment by lutfiatrash** [comment]
Any updates? 

> I go through the code i will migrate it soon

**Comment by AhmedAlYousif** [comment]
Sorry I've been out of the loop since long time ago, @MuhammedRefaat made a pull request to match with Flutter 2.0.

I will merge it, but please let me know if its what you need.

otherwise, I explained how I did this in this [article](https://medium.com/@ahmedalyousif/auto-change-ltr-direction-to-rtl-for-any-widget-b2fc229e0a0d)

**Comment by AhmedAlYousif** [comment]
OK, I went ahead and did the migration to null safety. I hope this doesn't break anything.
